---
- name: Fix Acpi Error
  block:
  # there is a problem:
  # "Failed to preset unit: Transport endpoint is not connected"
  # Workaround:
  # Source: https://github.com/OpenNebula/one/issues/5504
  # acpid -> acpi.path is the problem and have fixed

  # ToDo: Check
  # Add directive to avoid monitoring of acpi.path on containers.
  # Thanks to Nick Brown <nickbroon@gmail.com> and Simon Deziel <simon@sdeziel.info> for the patches.
  # (Closes: #1009301).

  - name: Install acpid
    ansible.builtin.apt:
      name: '{{ item }}'
      state: present
      update_cache: true
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
    with_items:
      - acpid
    environment:
      DEBIAN_FRONTEND: noninteractive
    when: ansible_os_family == 'Debian'

  - name: Fix acpi.path
    ansible.builtin.lineinfile:
      path: /lib/systemd/system/acpid.path
      insertafter: 'Description=ACPI Events Check'
      line: 'ConditionVirtualization=!container'

  - name: Restart acpi
    ansible.builtin.systemd:
      name: '{{ item }}'
      daemon_reload: true
      state: restarted
      enabled: true
      masked: false
    with_items:
      - acpid
      - acpid.path
    environment:
      DEBIAN_FRONTEND: noninteractive
    when: ansible_os_family == 'Debian'

  - name: Install acpi-support
    ansible.builtin.apt:
      name: '{{ item }}'
      state: present
      update_cache: true
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
    with_items:
      - acpi-support
    environment:
      DEBIAN_FRONTEND: noninteractive
    when: ansible_os_family == 'Debian'
  when: 
    - (install_kde_desktop is defined and install_kde_desktop) 
    - ansible_virtualization_role == "guest"
    - ansible_facts['lsb']['release'] == "22.04"
...
