---
- name: Install KDE Desktop
  block:
  # prevent that yes/no questions needs user-interaction
  - name: Assume-yes - write apt.conf.d/90forceyes
    ansible.builtin.blockinfile:
      path: /etc/apt/apt.conf.d/90assumeyes
      block: |
        APT::Get::Assume-Yes "true";
        APT::Get::allow-downgrades "true";
      create: true
      owner: root
      group: root
      mode: '0644'
    when: ansible_os_family == 'Debian'

  - name: Install kubuntu-desktop
    ansible.builtin.apt:
      name: '{{ item }}'
      state: present
      update_cache: true
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
    with_items:
      - kubuntu-desktop
      - kubuntu-restricted-extras
    environment:
      DEBIAN_FRONTEND: noninteractive
    when: ansible_os_family == 'Debian'

  - name: Translation files german
    ansible.builtin.apt:
      name: '{{ item }}'
      state: present
      update_cache: true
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
    with_items:
      - thunderbird-locale-de
      - libreoffice-help-de
      - language-pack-de-base
      - firefox-locale-de
      - language-pack-kde-de
      - libreoffice-l10n-de
      - aspell-de
    environment:
      DEBIAN_FRONTEND: noninteractive
    when: ansible_os_family == 'Debian'

  - name: Change language to de_DE
    ansible.builtin.copy:
      src: plasma-localerc
      dest: '/home/{{ default_user }}/.config/'
      owner: '{{ default_user }}'
      group: '{{ default_user }}'
      mode: '0644'

  # source1: https://unix.stackexchange.com/questions/534469/system-policy-prevents-control-of-network-connections
  # source2: https://askubuntu.com/questions/1237288/20-04-xrdp-kde-plasma-connect-issue
  # source3: https://github.com/neutrinolabs/xrdp/issues/1773#issuecomment-759419847
  - name: Polkit configuration - righst for NetworkManager, refresh, update, restart
    ansible.builtin.template:
      src: '{{ item.src }}'
      dest: '/etc/polkit-1/localauthority/50-local.d/{{ item.dest }}'
      owner: root
      group: root
      mode: '0644'
    with_items:
      - { src: xrdp-allow-colord.pkla.j2, dest: xrdp-allow-colord.pkla }
      - { src: xrdp-NetworkManager.pkla.j2, dest: xrdp-NetworkManager.pkla }
      - { src: xrdp-refresh-sources.pkla.j2, dest: xrdp-refresh-sources.pkla }
      - { src: xrdp-system-update.pkla.j2, dest: xrdp-system-update.pkla }
      - { src: xrdp-kde-restart.pkla.j2, dest: xrdp-kde-restart.pkla }

  # AD/LDAP Admin groups should be admin in KDE (polkit)
  - name: polkit AD/LDAP configuration
    ansible.builtin.template:
      src: 52-sssd-admin.conf.j2
      dest: "/etc/polkit-1/localauthority.conf.d/52-sssd-admin.conf"
      owner: "root"
      group: "root"
      mode: '0644'
    when: permitted_groups is defined and permitted_groups
  when: install_kde_desktop is defined and install_kde_desktop
...
