---
- name: Install Firefox
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10
  with_items:
    - firefox
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_os_family == 'Debian'

- name: Install FF Policy
  ansible.builtin.template:
    src: "firefox_policies.json.j2"
    dest: "/usr/lib/firefox/distribution/policies.json"
    owner: "root"
    group: "root"
    mode: "0644"
...
