---
- name: xrdp package installation
  block:
    # source: https://linuxize.com/post/how-to-install-xrdp-on-ubuntu-20-04/
  - name: install xrdp
    ansible.builtin.apt:
      name: '{{ item }}'
      state: present
      update_cache: True
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10
    with_items:
      - xrdp
    environment:
      DEBIAN_FRONTEND: noninteractive
    when: ansible_os_family == 'Debian'

  - name: adding xrdp to ssl-group
    ansible.builtin.user:
      name: xrdp
      groups: ssl-cert
      append: yes

  - name: restart xrdp service 
    ansible.builtin.systemd:
      name: xrdp
      daemon_reload: yes
      state: restarted
  when: hostvars['localhost']['install_kde_desktop'] is defined and hostvars['localhost']['install_kde_desktop'] == True

- name: Populate service facts
  service_facts:

- name: configure ssl
  block:
  - name: xrdp.ini add host certificate
    ansible.builtin.lineinfile:
      path: /etc/xrdp/xrdp.ini
      search_string: 'certificate='
      line: 'certificate=/etc/ssl/{{ cloudinit_fqdn }}.crt'
      create: yes
      owner: root
      group: root
      mode: '0644'
    when: ansible_os_family == 'Debian'

  - name: xrdp.ini add host keyfile
    ansible.builtin.lineinfile:
      path: /etc/xrdp/xrdp.ini
      search_string: 'key_file='
      line: 'key_file=/etc/ssl/{{ cloudinit_fqdn }}.key'
      create: yes
      owner: root
      group: root
      mode: '0644'
    when: ansible_os_family == 'Debian'

  - name: restart xrdp service 
    ansible.builtin.systemd:
      name: xrdp
      daemon_reload: yes
      state: restarted
  when: ("'step-renew.service' in services") and hostvars['localhost']['install_kde_desktop'] is defined and hostvars['localhost']['install_kde_desktop'] == True
...